test optimize
set opt_level=speed
target x86_64

;; Tests for I256 optimizations.
;; Backend support for I256 is not implemented, so these tests verify
;; that patterns produce extended constants rather than direct iconst.i256.

;; Self-identity patterns

function %bxor_self_i256(i256) -> i256 {
block0(v0: i256):
    v1 = bxor v0, v0
    return v1
    ; check: v2 = iconst.i64 0
    ; check: uextend
    ; check: return
}

function %isub_self_i256(i256) -> i256 {
block0(v0: i256):
    v1 = isub v0, v0
    return v1
    ; check: v2 = iconst.i64 0
    ; check: uextend
    ; check: return
}

function %eq_self_i256(i256) -> i8 {
block0(v0: i256):
    v1 = icmp eq v0, v0
    return v1
    ; check: v2 = iconst.i8 1
    ; check: return v2
}

function %ne_self_i256(i256) -> i8 {
block0(v0: i256):
    v1 = icmp ne v0, v0
    return v1
    ; check: v2 = iconst.i8 0
    ; check: return v2
}

;; Direct iconst.i256 parsing (verifies parser works)

function %iconst_i256_direct() -> i256 {
block0:
    v0 = iconst.i256 42
    return v0
    ; check: v0 = iconst.i256 42
    ; check: return v0
}

function %iconst_i256_negative() -> i256 {
block0:
    v0 = iconst.i256 -1
    return v0
    ; check: v0 = iconst.i256 -1
    ; check: return v0
}
